### ISSUE TITLE
Feature 1: List Case Types

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/casekartin-sankari#10]
#### User Story

* As a user, I should be able to add case types.

**Comment by csys-fresher-batch-2021** [comment]
#### Admin View
![image](https://user-images.githubusercontent.com/83430615/120869192-82d8db80-c5b3-11eb-8b81-a1f1c90f75e7.png)

**Comment by selva08sankari** [comment]
sir/madam is there any bug in this file?
