### ISSUE TITLE
Feature 3: User Login

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/casekartin-sankari#12]
#### User Story
* As a user, I should be able to login.

**Comment by csys-fresher-batch-2021** [comment]
#### Test Case 1: Valid Data [ PASSED]

![image](https://user-images.githubusercontent.com/83430615/120867744-2fb15980-c5b0-11eb-9693-00aab7030389.png)

**Comment by csys-fresher-batch-2021** [comment]
#### Test Case 3 :  Validation - Without role selection form is submitted [ FAILED] 
![image](https://user-images.githubusercontent.com/83430615/120867891-7a32d600-c5b0-11eb-92d7-9c71d7126740.png)

**Comment by csys-fresher-batch-2021** [comment]
#### Code

![image](https://user-images.githubusercontent.com/83430615/120868660-20cba680-c5b2-11eb-8e13-11d5e400904f.png)

**Comment by selva08sankari** [comment]
> #### Test Case 3 : Validation - Without role selection form is submitted [ FAILED]
> ![image](https://user-images.githubusercontent.com/83430615/120867891-7a32d600-c5b0-11eb-92d7-9c71d7126740.png)

Required is added and that issue fixed
![login](https://user-images.githubusercontent.com/82449841/121005800-cc8d1600-c7ad-11eb-9f80-933cde7f29f3.png)

**Comment by selva08sankari** [comment]
fixed the issues

> #### Code
> ![image](https://user-images.githubusercontent.com/83430615/120868660-20cba680-c5b2-11eb-8e13-11d5e400904f.png)

fixed the issues
