### ISSUE TITLE
Feature 6: Add Case Type

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/casekartin-sankari#15]
#### User Story
* As an admin user, I should be able to add case types.

**Comment by csys-fresher-batch-2021** [comment]
#### Test Case 1: Valid Data [ PASSED ]

![image](https://user-images.githubusercontent.com/83430615/120868913-bcf5ad80-c5b2-11eb-9e56-fb387fe85af1.png)

**Comment by csys-fresher-batch-2021** [comment]
#### Test Case 3: Invalid Data [ PASSED]
* 
![image](https://user-images.githubusercontent.com/83430615/120869106-42795d80-c5b3-11eb-874c-8055eee9b3f8.png)

**Comment by selva08sankari** [comment]
Error message showed
![Uploading alert message.png…]()

**Comment by selva08sankari** [comment]
> #### Test Case 2: Add the existing case [ FAILED]
> * Error Message not displayed
> 
> ![image](https://user-images.githubusercontent.com/83430615/120869040-11009200-c5b3-11eb-8fa3-c1c77431a4e6.png)

error message was displayed
![alert message](https://user-images.githubusercontent.com/82449841/121006578-a9af3180-c7ae-11eb-8ed3-db6a9a277b8b.png)

**Comment by selva08sankari** [comment]
I am fixed the bug and attached the screenshot above
