### ISSUE TITLE
Feature 8: View Registered Users

### ISSUE THREAD

**Issue by ghost** [csys-fresher-batch-2021/casekartin-sankari#17]
#### User Story

* As an admin user, I should be able to view registered users.

**Comment by csys-fresher-batch-2021** [comment]
![image](https://user-images.githubusercontent.com/83430615/120869572-612c2400-c5b4-11eb-9e82-ab99b577fa7d.png)

**Comment by csys-fresher-batch-2021** [comment]
Feature working as expected.
